apiVersion: apps/v1
kind: Deployment
metadata:
  name: mospi-front-cms
  labels:
    app: mospi-front-cms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mospi-front-cms
  template:
    metadata:
      labels:
        app: mospi-front-cms
    spec:
      containers:
        - name: mospi-front-cms
          image: release.enlightcloud.com/mospi/mospi-front-cms:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000

